### ISSUE TITLE
最新版IDEA无法安装插件

### ISSUE THREAD

**Issue by xiaosl-common** [x-hansong/CodeMaker#24]
![image](https://user-images.githubusercontent.com/63731217/130325936-334dee37-b208-4a24-897c-760b8752a224.png)
![image](https://user-images.githubusercontent.com/63731217/130325960-a723b387-3f97-4469-8e84-45da6de3d6d9.png)

最新版IDEA无法安装插件

**Comment by coderbean** [comment]
报错如下
```
2021-11-12 14:13:13,173 [  71218]   INFO - ta.index.VcsLogPersistentIndex - 191ms for indexing 522 commits in insgxengine
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
        at java.base/java.lang.String.charAt(String.java:693)
        at com.intellij.ide.plugins.PluginXmlPathResolver$Companion.toLoadPath$intellij_platform_core_impl(PluginXmlPathResolver.kt:53)
        at com.intellij.ide.plugins.PluginXmlPathResolver.resolvePath(PluginXmlPathResolver.kt:116)
        at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.processOldDependencies(IdeaPluginDescriptorImpl.kt:238)
        at com.intellij.ide.plugins.IdeaPluginDescriptorImpl.readExternal(IdeaPluginDescriptorImpl.kt:199)
        at com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromJar(PluginDescriptorLoader.kt:145)
        at com.intellij.ide.plugins.PluginDescriptorLoader.loadFromPluginDir(PluginDescriptorLoader.kt:237)
        at com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromFileOrDir(PluginDescriptorLoader.kt:192)
        at com.intellij.ide.plugins.PluginDescriptorLoader.loadDescriptorFromArtifact(PluginDescriptorLoader.kt:493)
        at com.intellij.ide.plugins.PluginInstaller.installFromDisk(PluginInstaller.java:235)
        at com.intellij.ide.plugins.PluginManagerConfigurable$InstallFromDiskAction.lambda$actionPerformed$1(PluginManagerConfigurable.java:1699)
        at com.intellij.ide.plugins.PluginInstaller.lambda$chooseAndInstall$0(PluginInstaller.java:442)
        at com.intellij.openapi.fileChooser.FileChooser.lambda$chooseFile$0(FileChooser.java:136)
        at com.intellij.ui.mac.MacPathChooserDialog.choose(MacPathChooserDialog.java:142)
        at com.intellij.openapi.fileChooser.FileChooser.chooseFiles(FileChooser.java:101)
        at com.intellij.openapi.fileChooser.FileChooser.chooseFile(FileChooser.java:136)
        at com.intellij.ide.plugins.PluginInstaller.chooseAndInstall(PluginInstaller.java:438)
        at com.intellij.ide.plugins.PluginManagerConfigurable$InstallFromDiskAction.actionPerformed(PluginManagerConfigurable.java:1698)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
        at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:252)
        at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:242)
        at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$2(ActionPopupStep.java:228)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1503)
        at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
        at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:186)
```

查了点资料：
https://youtrack.jetbrains.com/issue/IDEA-270963#focus=Comments-27-5056928.0-0

 vim 修改 了jar包里面的文件：`vim lib/CodeMaker-1.4.jar` `META-INF/plugin.xml`
删除了这一行，然后安装成功
```xml
<depends optional="true" config-file="">org.intellij.scala</depends>
```
安装成功
